import { DesignTokens } from "./tokens";

export const THEME_PRESETS: Record<string, DesignTokens> = {
  "glassmorphism-dark": {
    id: "glassmorphism-dark",
    name: "Glassmorphism Obsidian (Default)",
    category: "LUXURY",
    description: "Deep dark mode with frosted glass panels, ambient teal glow spheres, and 3D elevation.",
    version: "2.5.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 98,
    previewColor: "#0d9488",
    badge: "ACTIVE DEFAULT",
    styles: {
      bg: "bg-slate-950",
      text: "text-slate-100",
      headingFont: "font-serif",
      bodyFont: "font-sans",
      accent: "bg-teal-500",
      accentGlow: "rgba(45, 212, 191, 0.2)",
      cardBg: "bg-slate-900/65 backdrop-blur-xl border border-white/10",
      cardBorder: "border-white/10",
      cardHoverBorder: "hover:border-teal-500/40",
      headerBg: "bg-slate-950/75 backdrop-blur-2xl border-b border-white/10",
      footerBg: "bg-slate-950 border-t border-white/10",
      buttonBg: "bg-gradient-to-r from-teal-400 to-emerald-400 text-slate-950 font-bold",
      buttonText: "text-slate-950",
      pillBg: "bg-white/5 border border-white/10",
      pillText: "text-teal-300",
      radius: "rounded-3xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl shadow-teal-500/10",
    },
  },
  "apple-minimal-light": {
    id: "apple-minimal-light",
    name: "Apple Inspired Clean Light",
    category: "MINIMAL",
    description: "Ultra-clean white aesthetics inspired by Apple. Minimal typography, refined neutral borders, and subtle drop shadows.",
    version: "2.1.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#000000",
    badge: "POPULAR",
    styles: {
      bg: "bg-slate-50",
      text: "text-slate-900",
      headingFont: "font-sans font-bold tracking-tight",
      bodyFont: "font-sans",
      accent: "bg-slate-900",
      accentGlow: "rgba(0, 0, 0, 0.05)",
      cardBg: "bg-white border border-slate-200 shadow-sm",
      cardBorder: "border-slate-200",
      cardHoverBorder: "hover:border-slate-400 hover:shadow-md",
      headerBg: "bg-white/80 backdrop-blur-md border-b border-slate-200",
      footerBg: "bg-slate-100 border-t border-slate-200 text-slate-700",
      buttonBg: "bg-slate-900 text-white font-semibold",
      buttonText: "text-white",
      pillBg: "bg-slate-100 border border-slate-200",
      pillText: "text-slate-800",
      radius: "rounded-2xl",
      glassBlur: "backdrop-blur-md",
      shadow: "shadow-sm",
    },
  },
  "linear-cyber-dark": {
    id: "linear-cyber-dark",
    name: "Linear Cyber Monochrome",
    category: "CYBER",
    description: "Monochrome dark theme inspired by Linear.app. Indigo accents, crisp grid lines, and high-density typography.",
    version: "3.0.0",
    performanceScore: 98,
    seoScore: 100,
    accessibilityScore: 96,
    previewColor: "#6366f1",
    badge: "PRO TECH",
    styles: {
      bg: "bg-zinc-950",
      text: "text-zinc-100",
      headingFont: "font-mono tracking-tight",
      bodyFont: "font-sans",
      accent: "bg-indigo-600",
      accentGlow: "rgba(99, 102, 241, 0.25)",
      cardBg: "bg-zinc-900/90 border border-zinc-800",
      cardBorder: "border-zinc-800",
      cardHoverBorder: "hover:border-indigo-500/50",
      headerBg: "bg-zinc-950/90 border-b border-zinc-800 backdrop-blur-xl",
      footerBg: "bg-zinc-950 border-t border-zinc-800",
      buttonBg: "bg-indigo-600 text-white font-mono",
      buttonText: "text-white",
      pillBg: "bg-indigo-950/50 border border-indigo-500/30",
      pillText: "text-indigo-300",
      radius: "rounded-xl",
      glassBlur: "backdrop-blur-lg",
      shadow: "shadow-xl",
    },
  },
  "stripe-corporate-gradient": {
    id: "stripe-corporate-gradient",
    name: "Stripe Corporate Vibrant",
    category: "ENTERPRISE",
    description: "Rich corporate gradients inspired by Stripe. Cyan and purple highlights with high-converting CTA sections.",
    version: "2.4.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 97,
    previewColor: "#6366f1",
    badge: "ENTERPRISE",
    styles: {
      bg: "bg-slate-900",
      text: "text-slate-100",
      headingFont: "font-sans font-extrabold",
      bodyFont: "font-sans",
      accent: "bg-indigo-500",
      accentGlow: "rgba(99, 102, 241, 0.3)",
      cardBg: "bg-slate-800/80 border border-slate-700",
      cardBorder: "border-slate-700",
      cardHoverBorder: "hover:border-cyan-400",
      headerBg: "bg-slate-900/90 border-b border-slate-800 backdrop-blur-xl",
      footerBg: "bg-slate-950 border-t border-slate-800",
      buttonBg: "bg-gradient-to-r from-cyan-400 to-indigo-500 text-white font-bold",
      buttonText: "text-white",
      pillBg: "bg-cyan-500/10 border border-cyan-500/30",
      pillText: "text-cyan-300",
      radius: "rounded-2xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl",
    },
  },
  "dubai-gold-luxury": {
    id: "dubai-gold-luxury",
    name: "Dubai Gold Luxury Estate",
    category: "LUXURY",
    description: "Obsidian black and champagne gold luxury theme designed for ultra-high net worth property listings.",
    version: "3.1.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 96,
    previewColor: "#fbbf24",
    badge: "ULTRA LUXURY",
    styles: {
      bg: "bg-black",
      text: "text-amber-50",
      headingFont: "font-serif font-bold tracking-wide",
      bodyFont: "font-sans",
      accent: "bg-amber-400",
      accentGlow: "rgba(251, 191, 36, 0.25)",
      cardBg: "bg-zinc-950 border border-amber-500/20",
      cardBorder: "border-amber-500/20",
      cardHoverBorder: "hover:border-amber-400 hover:shadow-amber-500/20",
      headerBg: "bg-black/90 border-b border-amber-500/20 backdrop-blur-xl",
      footerBg: "bg-black border-t border-amber-500/20",
      buttonBg: "bg-gradient-to-r from-amber-300 via-amber-400 to-amber-500 text-black font-extrabold",
      buttonText: "text-black",
      pillBg: "bg-amber-500/10 border border-amber-500/30",
      pillText: "text-amber-300",
      radius: "rounded-3xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl shadow-amber-500/10",
    },
  },
  "neo-brutalism-bold": {
    id: "neo-brutalism-bold",
    name: "Neo Brutalism High-Contrast",
    category: "EDITORIAL",
    description: "High contrast, thick 3px black borders, drop shadows, and vibrant pop colors.",
    version: "1.8.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#f43f5e",
    badge: "EXPERIMENTAL",
    styles: {
      bg: "bg-yellow-50",
      text: "text-black",
      headingFont: "font-sans font-black uppercase",
      bodyFont: "font-mono",
      accent: "bg-rose-500",
      accentGlow: "none",
      cardBg: "bg-white border-4 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]",
      cardBorder: "border-4 border-black",
      cardHoverBorder: "hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all",
      headerBg: "bg-white border-b-4 border-black",
      footerBg: "bg-yellow-200 border-t-4 border-black text-black",
      buttonBg: "bg-rose-500 border-2 border-black text-black font-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]",
      buttonText: "text-black",
      pillBg: "bg-emerald-300 border-2 border-black",
      pillText: "text-black font-bold",
      radius: "rounded-none",
      glassBlur: "backdrop-none",
      shadow: "shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]",
    },
  },
  "scandinavian-minimal": {
    id: "scandinavian-minimal",
    name: "Scandinavian Soft Warm Muted",
    category: "MINIMAL",
    description: "Warm beige tones, muted sage greens, and relaxing aesthetic for organic living properties.",
    version: "2.0.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#10b981",
    badge: "ECO LIVING",
    styles: {
      bg: "bg-stone-100",
      text: "text-stone-800",
      headingFont: "font-serif",
      bodyFont: "font-sans",
      accent: "bg-emerald-700",
      accentGlow: "rgba(16, 185, 129, 0.1)",
      cardBg: "bg-stone-50 border border-stone-300 shadow-xs",
      cardBorder: "border-stone-300",
      cardHoverBorder: "hover:border-emerald-600",
      headerBg: "bg-stone-100/90 border-b border-stone-200 backdrop-blur-md",
      footerBg: "bg-stone-200 border-t border-stone-300 text-stone-700",
      buttonBg: "bg-stone-800 text-stone-100 font-medium",
      buttonText: "text-stone-100",
      pillBg: "bg-emerald-100 border border-emerald-300",
      pillText: "text-emerald-900",
      radius: "rounded-2xl",
      glassBlur: "backdrop-blur-md",
      shadow: "shadow-sm",
    },
  },
};
