import { DesignTokens } from "./tokens";

export const THEME_PRESETS: Record<string, DesignTokens> = {
  "glassmorphism-dark": {
    id: "glassmorphism-dark",
    name: "Glassmorphism Obsidian (Default)",
    category: "GLASSMORPHISM_DARK",
    description: "Deep dark mode with frosted glass panels, ambient teal glow spheres, and 3D elevation.",
    version: "2.5.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 98,
    previewColor: "#0d9488",
    badge: "ACTIVE DEFAULT",
    isFavorite: true,
    marketPattern: {
      region: "Global",
      sourceInspiration: "Linear & Apple Glass Physics",
      keyPatterns: ["Frosted glass card backdrop", "3D float physics", "Ambient glow lighting"],
    },
    styles: {
      bg: "bg-slate-950",
      text: "text-slate-100",
      headingFont: "font-serif",
      bodyFont: "font-sans",
      accent: "bg-teal-500",
      accentGlow: "rgba(45, 212, 191, 0.2)",
      cardBg: "bg-slate-900/65 backdrop-blur-xl border border-white/10",
      cardBorder: "border-white/10",
      cardHoverBorder: "hover:border-teal-500/40",
      headerBg: "bg-slate-950/75 backdrop-blur-2xl border-b border-white/10",
      footerBg: "bg-slate-950 border-t border-white/10",
      buttonBg: "bg-gradient-to-r from-teal-400 to-emerald-400 text-slate-950 font-bold",
      buttonText: "text-slate-950",
      pillBg: "bg-white/5 border border-white/10",
      pillText: "text-teal-300",
      radius: "rounded-3xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl shadow-teal-500/10",
    },
  },
  "bayut-dubai-luxury": {
    id: "bayut-dubai-luxury",
    name: "Bayut & PropertyFinder Middle East Hub",
    category: "ENTERPRISE_BAYUT",
    description: "High-yield investment badges, 360° virtual tour highlights, and EMAAR masterplan highlights.",
    version: "3.2.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 99,
    previewColor: "#059669",
    badge: "BAYUT INSPIRED",
    isFavorite: true,
    marketPattern: {
      region: "Middle East (UAE & Saudi Arabia)",
      sourceInspiration: "Bayut & PropertyFinder UX Patterns",
      keyPatterns: ["High-Yield ROI badges", "360° Virtual Tour highlights", "Direct RERA masterplan links"],
    },
    styles: {
      bg: "bg-slate-950",
      text: "text-slate-100",
      headingFont: "font-serif font-bold",
      bodyFont: "font-sans",
      accent: "bg-emerald-500",
      accentGlow: "rgba(16, 185, 129, 0.25)",
      cardBg: "bg-slate-900/80 border border-emerald-500/20",
      cardBorder: "border-emerald-500/20",
      cardHoverBorder: "hover:border-emerald-400",
      headerBg: "bg-slate-950/90 border-b border-emerald-500/20 backdrop-blur-xl",
      footerBg: "bg-slate-950 border-t border-emerald-500/20",
      buttonBg: "bg-gradient-to-r from-emerald-400 to-teal-400 text-slate-950 font-bold",
      buttonText: "text-slate-950",
      pillBg: "bg-emerald-500/10 border border-emerald-500/30",
      pillText: "text-emerald-300",
      radius: "rounded-2xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl shadow-emerald-500/10",
    },
  },
  "zillow-map-first": {
    id: "zillow-map-first",
    name: "Zillow & Redfin Map-First US Grid",
    category: "MAP_FIRST_ZILLOW",
    description: "Map-centric location search, WalkScore metrics, and high-density photo grid view.",
    version: "2.8.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#2563eb",
    badge: "ZILLOW INSPIRED",
    styles: {
      bg: "bg-slate-950",
      text: "text-slate-100",
      headingFont: "font-sans font-bold",
      bodyFont: "font-sans",
      accent: "bg-blue-600",
      accentGlow: "rgba(37, 99, 235, 0.25)",
      cardBg: "bg-slate-900 border border-blue-500/20",
      cardBorder: "border-blue-500/20",
      cardHoverBorder: "hover:border-blue-400",
      headerBg: "bg-slate-950/90 border-b border-blue-500/20 backdrop-blur-xl",
      footerBg: "bg-slate-950 border-t border-blue-500/20",
      buttonBg: "bg-blue-600 text-white font-bold",
      buttonText: "text-white",
      pillBg: "bg-blue-500/10 border border-blue-500/30",
      pillText: "text-blue-300",
      radius: "rounded-xl",
      glassBlur: "backdrop-blur-lg",
      shadow: "shadow-xl",
    },
    marketPattern: {
      region: "North America (US & Canada)",
      sourceInspiration: "Zillow & Redfin Map Search",
      keyPatterns: ["WalkScore® location integration", "Split-screen map view", "Instant filter sliders"],
    },
  },
  "compass-minimal-luxury": {
    id: "compass-minimal-luxury",
    name: "Compass & Apple Minimal Luxury",
    category: "MINIMAL_COMPASS",
    description: "Monochrome elegance, refined typography, and high-end editorial photography framing.",
    version: "2.1.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#000000",
    badge: "COMPASS INSPIRED",
    styles: {
      bg: "bg-slate-50",
      text: "text-slate-900",
      headingFont: "font-sans font-bold tracking-tight",
      bodyFont: "font-sans",
      accent: "bg-slate-900",
      accentGlow: "rgba(0, 0, 0, 0.05)",
      cardBg: "bg-white border border-slate-200 shadow-sm",
      cardBorder: "border-slate-200",
      cardHoverBorder: "hover:border-slate-400 hover:shadow-md",
      headerBg: "bg-white/80 backdrop-blur-md border-b border-slate-200",
      footerBg: "bg-slate-100 border-t border-slate-200 text-slate-700",
      buttonBg: "bg-slate-900 text-white font-semibold",
      buttonText: "text-white",
      pillBg: "bg-slate-100 border border-slate-200",
      pillText: "text-slate-800",
      radius: "rounded-2xl",
      glassBlur: "backdrop-blur-md",
      shadow: "shadow-sm",
    },
    marketPattern: {
      region: "Global Luxury",
      sourceInspiration: "Compass Real Estate & Apple HCI",
      keyPatterns: ["Monochrome elegance", "Ultra-wide hero layouts", "High contrast black-white text"],
    },
  },
  "dubai-gold-luxury": {
    id: "dubai-gold-luxury",
    name: "Dubai Gold Luxury Estate",
    category: "LUXURY_ESTATE",
    description: "Obsidian black and champagne gold luxury theme designed for ultra-high net worth property listings.",
    version: "3.1.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 96,
    previewColor: "#fbbf24",
    badge: "ULTRA LUXURY",
    isFavorite: true,
    marketPattern: {
      region: "Middle East & Europe",
      sourceInspiration: "Sotheby's & Knight Frank",
      keyPatterns: ["Champagne gold foil accents", "Obsidian black contrast", "Concierge lead capture"],
    },
    styles: {
      bg: "bg-black",
      text: "text-amber-50",
      headingFont: "font-serif font-bold tracking-wide",
      bodyFont: "font-sans",
      accent: "bg-amber-400",
      accentGlow: "rgba(251, 191, 36, 0.25)",
      cardBg: "bg-zinc-950 border border-amber-500/20",
      cardBorder: "border-amber-500/20",
      cardHoverBorder: "hover:border-amber-400 hover:shadow-amber-500/20",
      headerBg: "bg-black/90 border-b border-amber-500/20 backdrop-blur-xl",
      footerBg: "bg-black border-t border-amber-500/20",
      buttonBg: "bg-gradient-to-r from-amber-300 via-amber-400 to-amber-500 text-black font-extrabold",
      buttonText: "text-black",
      pillBg: "bg-amber-500/10 border border-amber-500/30",
      pillText: "text-amber-300",
      radius: "rounded-3xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl shadow-amber-500/10",
    },
  },
  "scandinavian-minimal": {
    id: "scandinavian-minimal",
    name: "Scandinavian Eco Living (Idealista)",
    category: "ECO_SUSTAINABLE",
    description: "Warm beige tones, muted sage greens, and relaxing aesthetic inspired by Idealista & Immobilienscout24.",
    version: "2.0.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#10b981",
    badge: "IDEALISTA INSPIRED",
    marketPattern: {
      region: "Europe (Spain, Germany, Sweden)",
      sourceInspiration: "Idealista & Immobilienscout24",
      keyPatterns: ["Energy efficiency ratings A+", "Eco-living features", "Warm beige neutral palettes"],
    },
    styles: {
      bg: "bg-stone-100",
      text: "text-stone-800",
      headingFont: "font-serif",
      bodyFont: "font-sans",
      accent: "bg-emerald-700",
      accentGlow: "rgba(16, 185, 129, 0.1)",
      cardBg: "bg-stone-50 border border-stone-300 shadow-xs",
      cardBorder: "border-stone-300",
      cardHoverBorder: "hover:border-emerald-600",
      headerBg: "bg-stone-100/90 border-b border-stone-200 backdrop-blur-md",
      footerBg: "bg-stone-200 border-t border-stone-300 text-stone-700",
      buttonBg: "bg-stone-800 text-stone-100 font-medium",
      buttonText: "text-stone-100",
      pillBg: "bg-emerald-100 border border-emerald-300",
      pillText: "text-emerald-900",
      radius: "rounded-2xl",
      glassBlur: "backdrop-blur-md",
      shadow: "shadow-sm",
    },
  },
};
