import { DesignTokens } from "./tokens";

export const THEME_PRESETS: Record<string, DesignTokens> = {
  "glassmorphism-dark": {
    id: "glassmorphism-dark",
    name: "Glassmorphism Obsidian (Default)",
    category: "GLASSMORPHISM_DARK",
    description: "Deep dark mode with frosted glass panels, ambient teal glow spheres, and 3D elevation.",
    version: "2.5.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 98,
    previewColor: "#0d9488",
    badge: "ACTIVE DEFAULT",
    isFavorite: true,
    marketPattern: {
      region: "Global",
      sourceInspiration: "Linear & Apple Glass Physics",
      keyPatterns: ["Frosted glass card backdrop", "3D float physics", "Ambient glow lighting"],
    },
    layoutSchema: {
      heroVariant: "GLASS_AURORA",
      cardVariant: "GLASS_3D_HOVER",
      searchVariant: "AI_CONVERSATIONAL",
      sectionOrder: [
        "HERO",
        "CITIES",
        "FEATURED_PROJECTS",
        "PREMIUM_PROPERTIES",
        "VIDEO_REELS",
        "DEVELOPER_PARTNERS",
        "MARKET_INSIGHTS",
        "TESTIMONIALS",
        "AWARDS",
        "CONSULTATION_BANNER",
      ],
    },
    styles: {
      bg: "bg-slate-950",
      text: "text-slate-100",
      headingFont: "font-serif",
      bodyFont: "font-sans",
      accent: "bg-teal-500",
      accentGlow: "rgba(45, 212, 191, 0.2)",
      cardBg: "bg-slate-900/65 backdrop-blur-xl border border-white/10",
      cardBorder: "border-white/10",
      cardHoverBorder: "hover:border-teal-500/40",
      headerBg: "bg-slate-950/75 backdrop-blur-2xl border-b border-white/10",
      footerBg: "bg-slate-950 border-t border-white/10",
      buttonBg: "bg-gradient-to-r from-teal-400 to-emerald-400 text-slate-950 font-bold",
      buttonText: "text-slate-950",
      pillBg: "bg-white/5 border border-white/10",
      pillText: "text-teal-300",
      radius: "rounded-3xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl shadow-teal-500/10",
    },
  },
  "apple-minimal-light": {
    id: "apple-minimal-light",
    name: "Apple Inspired Clean Light",
    category: "APPLE_MINIMAL_LIGHT",
    description: "Ultra-clean white aesthetics inspired by Apple. Minimal typography, product presentation layout, and refined neutral borders.",
    version: "2.1.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#000000",
    badge: "APPLE INSPIRED",
    isFavorite: true,
    marketPattern: {
      region: "Global Luxury",
      sourceInspiration: "Apple HCI & Compass Minimal",
      keyPatterns: ["San Francisco typography", "Product presentation cards", "Ultra-wide white space"],
    },
    layoutSchema: {
      heroVariant: "APPLE_MINIMAL_LIGHT",
      cardVariant: "APPLE_PRODUCT_SLAB",
      searchVariant: "CLEAN_SEARCH_BAR",
      sectionOrder: [
        "HERO",
        "PREMIUM_PROPERTIES",
        "FEATURED_PROJECTS",
        "DEVELOPER_PARTNERS",
        "TESTIMONIALS",
        "AWARDS",
        "CONSULTATION_BANNER",
      ],
    },
    styles: {
      bg: "bg-slate-50",
      text: "text-slate-900",
      headingFont: "font-sans font-bold tracking-tight",
      bodyFont: "font-sans",
      accent: "bg-slate-900",
      accentGlow: "rgba(0, 0, 0, 0.05)",
      cardBg: "bg-white border border-slate-200 shadow-sm",
      cardBorder: "border-slate-200",
      cardHoverBorder: "hover:border-slate-400 hover:shadow-md",
      headerBg: "bg-white/80 backdrop-blur-md border-b border-slate-200",
      footerBg: "bg-slate-100 border-t border-slate-200 text-slate-700",
      buttonBg: "bg-slate-900 text-white font-semibold",
      buttonText: "text-white",
      pillBg: "bg-slate-100 border border-slate-200",
      pillText: "text-slate-800",
      radius: "rounded-2xl",
      glassBlur: "backdrop-blur-md",
      shadow: "shadow-sm",
    },
  },
  "dubai-gold-luxury": {
    id: "dubai-gold-luxury",
    name: "Dubai Gold Luxury Estate",
    category: "DUBAI_GOLD_LUXURY",
    description: "Obsidian black and champagne gold luxury theme designed for ultra-high net worth property listings.",
    version: "3.1.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 96,
    previewColor: "#fbbf24",
    badge: "ULTRA LUXURY",
    isFavorite: true,
    marketPattern: {
      region: "Middle East & Europe",
      sourceInspiration: "Bayut & Sotheby's Luxury",
      keyPatterns: ["Champagne gold foil accents", "Video skyline hero", "Concierge lead capture"],
    },
    layoutSchema: {
      heroVariant: "DUBAI_VIDEO_LUXURY",
      cardVariant: "DUBAI_GOLD_CARD",
      searchVariant: "COMPACT_OVERLAY",
      sectionOrder: [
        "HERO",
        "DEVELOPER_PARTNERS",
        "FEATURED_PROJECTS",
        "PREMIUM_PROPERTIES",
        "VIDEO_REELS",
        "MARKET_INSIGHTS",
        "AWARDS",
        "TESTIMONIALS",
        "CONSULTATION_BANNER",
      ],
    },
    styles: {
      bg: "bg-black",
      text: "text-amber-50",
      headingFont: "font-serif font-bold tracking-wide",
      bodyFont: "font-sans",
      accent: "bg-amber-400",
      accentGlow: "rgba(251, 191, 36, 0.25)",
      cardBg: "bg-zinc-950 border border-amber-500/20",
      cardBorder: "border-amber-500/20",
      cardHoverBorder: "hover:border-amber-400 hover:shadow-amber-500/20",
      headerBg: "bg-black/90 border-b border-amber-500/20 backdrop-blur-xl",
      footerBg: "bg-black border-t border-amber-500/20",
      buttonBg: "bg-gradient-to-r from-amber-300 via-amber-400 to-amber-500 text-black font-extrabold",
      buttonText: "text-black",
      pillBg: "bg-amber-500/10 border border-amber-500/30",
      pillText: "text-amber-300",
      radius: "rounded-3xl",
      glassBlur: "backdrop-blur-xl",
      shadow: "shadow-2xl shadow-amber-500/10",
    },
  },
  "linear-cyber-dark": {
    id: "linear-cyber-dark",
    name: "Linear Cyber Monochrome",
    category: "LINEAR_CYBER_DARK",
    description: "Monochrome dark theme inspired by Linear.app. Indigo accents, crisp grid lines, and high-density typography.",
    version: "3.0.0",
    performanceScore: 98,
    seoScore: 100,
    accessibilityScore: 96,
    previewColor: "#6366f1",
    badge: "PRO TECH",
    marketPattern: {
      region: "Global",
      sourceInspiration: "Linear.app UI & Vercel",
      keyPatterns: ["Monochrome grid aesthetics", "High-density data tables", "Indigo glow highlights"],
    },
    layoutSchema: {
      heroVariant: "LINEAR_GRID_TECH",
      cardVariant: "LINEAR_MONOCHROME_CARD",
      searchVariant: "AI_CONVERSATIONAL",
      sectionOrder: [
        "HERO",
        "MARKET_INSIGHTS",
        "PREMIUM_PROPERTIES",
        "FEATURED_PROJECTS",
        "DEVELOPER_PARTNERS",
        "TESTIMONIALS",
        "CONSULTATION_BANNER",
      ],
    },
    styles: {
      bg: "bg-zinc-950",
      text: "text-zinc-100",
      headingFont: "font-mono tracking-tight",
      bodyFont: "font-sans",
      accent: "bg-indigo-600",
      accentGlow: "rgba(99, 102, 241, 0.25)",
      cardBg: "bg-zinc-900/90 border border-zinc-800",
      cardBorder: "border-zinc-800",
      cardHoverBorder: "hover:border-indigo-500/50",
      headerBg: "bg-zinc-950/90 border-b border-zinc-800 backdrop-blur-xl",
      footerBg: "bg-zinc-950 border-t border-zinc-800",
      buttonBg: "bg-indigo-600 text-white font-mono",
      buttonText: "text-white",
      pillBg: "bg-indigo-950/50 border border-indigo-500/30",
      pillText: "text-indigo-300",
      radius: "rounded-xl",
      glassBlur: "backdrop-blur-lg",
      shadow: "shadow-xl",
    },
  },
  "zillow-map-first": {
    id: "zillow-map-first",
    name: "Zillow & Redfin Map-First US Grid",
    category: "MAP_FIRST_ZILLOW",
    description: "Map-centric location search, WalkScore metrics, and high-density photo grid view.",
    version: "2.8.0",
    performanceScore: 99,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#2563eb",
    badge: "ZILLOW INSPIRED",
    marketPattern: {
      region: "North America (US & Canada)",
      sourceInspiration: "Zillow & Redfin Map Search",
      keyPatterns: ["WalkScore® location integration", "Split-screen map view", "Instant filter sliders"],
    },
    layoutSchema: {
      heroVariant: "MAP_FIRST_ZILLOW",
      cardVariant: "APPLE_PRODUCT_SLAB",
      searchVariant: "MAP_INTERACTIVE",
      sectionOrder: [
        "HERO",
        "CITIES",
        "PREMIUM_PROPERTIES",
        "MARKET_INSIGHTS",
        "TESTIMONIALS",
        "CONSULTATION_BANNER",
      ],
    },
    styles: {
      bg: "bg-slate-950",
      text: "text-slate-100",
      headingFont: "font-sans font-bold",
      bodyFont: "font-sans",
      accent: "bg-blue-600",
      accentGlow: "rgba(37, 99, 235, 0.25)",
      cardBg: "bg-slate-900 border border-blue-500/20",
      cardBorder: "border-blue-500/20",
      cardHoverBorder: "hover:border-blue-400",
      headerBg: "bg-slate-950/90 border-b border-blue-500/20 backdrop-blur-xl",
      footerBg: "bg-slate-950 border-t border-blue-500/20",
      buttonBg: "bg-blue-600 text-white font-bold",
      buttonText: "text-white",
      pillBg: "bg-blue-500/10 border border-blue-500/30",
      pillText: "text-blue-300",
      radius: "rounded-xl",
      glassBlur: "backdrop-blur-lg",
      shadow: "shadow-xl",
    },
  },
  "neo-brutalism-bold": {
    id: "neo-brutalism-bold",
    name: "Neo Brutalism High-Contrast",
    category: "NEO_BRUTALISM_BOLD",
    description: "High contrast, thick 4px black borders, drop shadows, and vibrant pop colors.",
    version: "1.8.0",
    performanceScore: 100,
    seoScore: 100,
    accessibilityScore: 100,
    previewColor: "#f43f5e",
    badge: "EXPERIMENTAL",
    marketPattern: {
      region: "Global Creative",
      sourceInspiration: "Framer & Webflow Neo-Brutalism",
      keyPatterns: ["4px thick solid black borders", "Raw drop shadows", "High-contrast typography"],
    },
    layoutSchema: {
      heroVariant: "NEO_BRUTALIST",
      cardVariant: "NEO_BRUTAL_BOX",
      searchVariant: "CLEAN_SEARCH_BAR",
      sectionOrder: [
        "HERO",
        "PREMIUM_PROPERTIES",
        "CITIES",
        "DEVELOPER_PARTNERS",
        "TESTIMONIALS",
        "AWARDS",
        "CONSULTATION_BANNER",
      ],
    },
    styles: {
      bg: "bg-yellow-50",
      text: "text-black",
      headingFont: "font-sans font-black uppercase",
      bodyFont: "font-mono",
      accent: "bg-rose-500",
      accentGlow: "none",
      cardBg: "bg-white border-4 border-black shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]",
      cardBorder: "border-4 border-black",
      cardHoverBorder: "hover:translate-x-1 hover:translate-y-1 hover:shadow-none transition-all",
      headerBg: "bg-white border-b-4 border-black",
      footerBg: "bg-yellow-200 border-t-4 border-black text-black",
      buttonBg: "bg-rose-500 border-2 border-black text-black font-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]",
      buttonText: "text-black",
      pillBg: "bg-emerald-300 border-2 border-black",
      pillText: "text-black font-bold",
      radius: "rounded-none",
      glassBlur: "backdrop-none",
      shadow: "shadow-[6px_6px_0px_0px_rgba(0,0,0,1)]",
    },
  },
};
